apiVersion: v2
name: bleh
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: nginx
    version: 0.1.0
    # this needs to be the url where the assets are hosted; must contain an index.yaml
    repository: https://nnethercott.github.io/helm-charts-practice/
